### ISSUE TITLE
Counter Ashiyaap reset ke 0 tiap browser refresh

### ISSUE THREAD

**Issue by Axection** [mirukusheki/ashiyaap#10]
Suggest bisa pake js-cookie ato localstorage biar persist counternya.

**Comment by adamsh231** [comment]
> Suggest bisa pake js-cookie ato localstorage biar persist counternya.

wkwk menurut ane gaada esensinya, dikate wirid-an disimpen di cookie counternya

**Comment by mirukusheki** [comment]
Bener menurut @adamsh231 ga ada esensi yang jelas untuk menyimpan cookie di website seperti ini karena tujuan dari website ini hanya untuk sekali visit saja, jadi ketika di refresh langsung direset lagi ke 0

**Comment by Axection** [comment]
well sesuatu yang emang udah nirfaedah bisa dimaksimalin sih nirfaedahnya wkkw

but okay then.
